# Generated by Django 6.0.5 on 2026-06-25 19:39

import core.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('price', models.IntegerField(verbose_name='Preço (Ouro)')),
                ('item_type', models.CharField(choices=[('Consumível', 'Consumível'), ('Equipamento', 'Equipamento'), ('Cosmético', 'Cosmético')], max_length=50, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição do Item')),
                ('bonus_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Bônus')),
                ('icon', models.CharField(default='📦', max_length=10, verbose_name='Ícone')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pontos de Vida')),
                ('max_hp', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='HP Máximo')),
                ('level', models.IntegerField(default=1, verbose_name='Nível')),
                ('xp', models.IntegerField(default=0, verbose_name='Experiência')),
                ('total_xp', models.IntegerField(default=0, verbose_name='XP Total')),
                ('gold', models.IntegerField(default=0, verbose_name='Ouro')),
                ('clothesVariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Roupa')),
                ('eyesVariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Olhos')),
                ('glassesVariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Óculos')),
                ('hairVariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Cabelo')),
                ('hatVariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Boné')),
                ('mouthVariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Boca')),
                ('beardVariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Barba')),
                ('hairColor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor de Cabelo')),
                ('clothesColor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor da Roupa')),
                ('eyesColor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor dos Olhos')),
                ('glassesColor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor dos Óculos')),
                ('hatColor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor do boné')),
                ('mouthColor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor da boca')),
                ('skinColor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor da pele')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('due_date', models.DateTimeField(verbose_name='Data de Entrega')),
                ('difficulty', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], max_length=10, verbose_name='Dificuldade')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('overdue_processed', models.BooleanField(default=False, verbose_name='Atraso Processado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ActiveEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, verbose_name='Tipo')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effects', to='core.avatar')),
            ],
            options={
                'unique_together': {('avatar', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Bloqueado', 'Bloqueado')], default='Pendente', max_length=20)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Equipado')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.avatar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'verbose_name': 'Item no Inventário',
                'verbose_name_plural': 'Itens no Inventário',
                'unique_together': {('avatar', 'item')},
            },
        ),
    ]
